// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.11.0 (commit 49ccb7ac2ae18042057c844591c9749532bc691a).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import and reexport all reducer arg types
import AddUpdate from "./add_update_reducer";
export { AddUpdate };
import IdentityConnected from "./identity_connected_reducer";
export { IdentityConnected };
import IdentityDisconnected from "./identity_disconnected_reducer";
export { IdentityDisconnected };
import SendMessage from "./send_message_reducer";
export { SendMessage };
import SetName from "./set_name_reducer";
export { SetName };
import UpdateMouseState from "./update_mouse_state_reducer";
export { UpdateMouseState };
import UpdateStatus from "./update_status_reducer";
export { UpdateStatus };

// Import and reexport all procedure arg types

// Import and reexport all table handle types
import AdminRow from "./admin_table";
export { AdminRow };
import CurrentStatusRow from "./current_status_table";
export { CurrentStatusRow };
import MessageRow from "./message_table";
export { MessageRow };
import MouseStateRow from "./mouse_state_table";
export { MouseStateRow };
import PollRow from "./poll_table";
export { PollRow };
import PollOptionRow from "./poll_option_table";
export { PollOptionRow };
import PollVoteRow from "./poll_vote_table";
export { PollVoteRow };
import UpdateLogRow from "./update_log_table";
export { UpdateLogRow };
import UserRow from "./user_table";
export { UserRow };

// Import and reexport all types
import Admin from "./admin_type";
export { Admin };
import CurrentStatus from "./current_status_type";
export { CurrentStatus };
import Message from "./message_type";
export { Message };
import MouseState from "./mouse_state_type";
export { MouseState };
import Poll from "./poll_type";
export { Poll };
import PollOption from "./poll_option_type";
export { PollOption };
import PollVote from "./poll_vote_type";
export { PollVote };
import UpdateLog from "./update_log_type";
export { UpdateLog };
import User from "./user_type";
export { User };

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema(
  __table({
    name: 'admin',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'admin_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, AdminRow),
  __table({
    name: 'current_status',
    indexes: [
      { name: 'id', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'current_status_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CurrentStatusRow),
  __table({
    name: 'message',
    indexes: [
    ],
    constraints: [
    ],
  }, MessageRow),
  __table({
    name: 'mouse_state',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'mouse_state_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, MouseStateRow),
  __table({
    name: 'poll',
    indexes: [
      { name: 'poll_id', algorithm: 'btree', columns: [
        'pollId',
      ] },
    ],
    constraints: [
      { name: 'poll_poll_id_key', constraint: 'unique', columns: ['pollId'] },
    ],
  }, PollRow),
  __table({
    name: 'poll_option',
    indexes: [
      { name: 'option_id', algorithm: 'btree', columns: [
        'optionId',
      ] },
    ],
    constraints: [
      { name: 'poll_option_option_id_key', constraint: 'unique', columns: ['optionId'] },
    ],
  }, PollOptionRow),
  __table({
    name: 'poll_vote',
    indexes: [
      { name: 'vote_id', algorithm: 'btree', columns: [
        'voteId',
      ] },
    ],
    constraints: [
      { name: 'poll_vote_vote_id_key', constraint: 'unique', columns: ['voteId'] },
    ],
  }, PollVoteRow),
  __table({
    name: 'update_log',
    indexes: [
      { name: 'update_id', algorithm: 'btree', columns: [
        'updateId',
      ] },
    ],
    constraints: [
      { name: 'update_log_update_id_key', constraint: 'unique', columns: ['updateId'] },
    ],
  }, UpdateLogRow),
  __table({
    name: 'user',
    indexes: [
      { name: 'identity', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'user_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, UserRow),
);

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_update", AddUpdate),
  __reducerSchema("send_message", SendMessage),
  __reducerSchema("set_name", SetName),
  __reducerSchema("update_mouse_state", UpdateMouseState),
  __reducerSchema("update_status", UpdateStatus),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.11.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. */
export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

