// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.object("MouseState", {
  identity: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  leftButtonDown: __t.bool(),
  rightButtonDown: __t.bool(),
  middleButtonDown: __t.bool(),
  scrollX: __t.f32(),
  scrollY: __t.f32(),
  isDragging: __t.bool(),
  hoveredElement: __t.string(),
  viewportWidth: __t.f32(),
  viewportHeight: __t.f32(),
  lastUpdated: __t.timestamp(),
});


