// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type PollVote = {
  voteId: bigint,
  voter: Identity,
  pollId: bigint,
  optionId: bigint,
  votedAt: bigint,
};

/**
 * A namespace for generated helper functions.
 */
export namespace PollVote {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("voteId", AlgebraicType.createU64Type()),
      new ProductTypeElement("voter", AlgebraicType.createIdentityType()),
      new ProductTypeElement("pollId", AlgebraicType.createU64Type()),
      new ProductTypeElement("optionId", AlgebraicType.createU64Type()),
      new ProductTypeElement("votedAt", AlgebraicType.createU64Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: PollVote): void {
    PollVote.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): PollVote {
    return PollVote.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


