// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  CallReducerFlags,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
  // @ts-ignore
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { UpdateLog } from "./update_log_type";
// @ts-ignore
import { EventContext, Reducer, RemoteReducers, RemoteTables } from ".";

/**
 * Table handle for the table `update_log`.
 *
 * Obtain a handle from the [`updateLog`] property on [`RemoteTables`],
 * like `ctx.db.updateLog`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.updateLog.on_insert(...)`.
 */
export class UpdateLogTableHandle {
  tableCache: TableCache<UpdateLog>;

  constructor(tableCache: TableCache<UpdateLog>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<UpdateLog> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `update_id` unique index on the table `update_log`,
   * which allows point queries on the field of the same name
   * via the [`UpdateLogUpdateIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.updateLog.update_id().find(...)`.
   *
   * Get a handle on the `update_id` unique index on the table `update_log`.
   */
  update_id = {
    // Find the subscribed row whose `update_id` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): UpdateLog | undefined => {
      for (let row of this.tableCache.iter()) {
        if (deepEqual(row.update_id, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: UpdateLog) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: UpdateLog) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: UpdateLog) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: UpdateLog) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: UpdateLog, newRow: UpdateLog) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: UpdateLog, newRow: UpdateLog) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
