// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Poll = {
  pollId: bigint,
  question: string,
  createdBy: Identity,
  createdAt: bigint,
  expiresAt: bigint | undefined,
  active: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Poll {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("pollId", AlgebraicType.createU64Type()),
      new ProductTypeElement("question", AlgebraicType.createStringType()),
      new ProductTypeElement("createdBy", AlgebraicType.createIdentityType()),
      new ProductTypeElement("createdAt", AlgebraicType.createU64Type()),
      new ProductTypeElement("expiresAt", AlgebraicType.createOptionType(AlgebraicType.createU64Type())),
      new ProductTypeElement("active", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Poll): void {
    Poll.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Poll {
    return Poll.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


